-- Insert categories
INSERT INTO public.categories (name, user_id) VALUES
('Acciones', NULL),
('Lugares', NULL),
('Personas', NULL),
('Comida', NULL),
('Emociones', NULL)
ON CONFLICT (name) DO NOTHING;

-- Insert pictograms
-- Note: user_id is NULL for default pictograms
-- You might need to adjust category_id based on the actual IDs generated by your database

INSERT INTO public.pictograms (name, image_url, audio_url, category_id, user_id) VALUES
('comer', 'https://api.arasaac.org/api/pictograms/6456', NULL, (SELECT id FROM public.categories WHERE name = 'Acciones'), NULL),
('beber', 'https://api.arasaac.org/api/pictograms/6061', NULL, (SELECT id FROM public.categories WHERE name = 'Acciones'), NULL),
('casa', 'https://api.arasaac.org/api/pictograms/6964', NULL, (SELECT id FROM public.categories WHERE name = 'Lugares'), NULL)
ON CONFLICT (name) DO NOTHING;