name: app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.8
  flutter_tts: ^4.0.2
  provider: ^6.1.2
  go_router: ^14.2.1
  reorderable_grid_view: ^2.0.0
  uuid: ^4.4.0
  speech_to_text: ^6.6.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
